### ISSUE TITLE
regression from 0.9.0 to 0.9.1 (and higher) in handling shell commands

### ISSUE THREAD

**Issue by andreasgem** [goeuro/myke#82]
Running `myke test` on a yaml file with this content
```
project: test
tasks:
  test:
    cmd: |-
      echo SOMETHING=$(echo test)
```
provides this result with myke 0.9.0: 
```
++ echo test
+ echo SOMETHING=test
SOMETHING=test
• mobileweb/test: Completed, Took: 11.366067ms
```
With myke 0.9.1 and higher the output is however an error:
```
sh: -c: line 0: syntax error near unexpected token `('
⨯ mobileweb/test: Failed, Took: 8.97756ms
⨯ error                     error=error running command: exit status 2
```

Expected behaviour: Same behaviour as with myke 0.9.0
