### ISSUE TITLE
Bring --loglevel back

### ISSUE THREAD

**Issue by licarth** [goeuro/myke#83]
Or something that allows to tell `myke` to be quiet.

Example : Calling a util task to get ip from kubeconfig.

```
tasks:
  my_task:
    cmd: |-
      netIp=`$myke --loglevel fatal _get_ip`
  _get_ip:
    cmd: |-
      echo `cat $KUBECONFIG | grep server | cut -d: -f2 | xargs`
```

Could also be :
```
myke --quiet _get_ip
```
