### ISSUE TITLE
naming a taks off yield a task named false

### ISSUE THREAD

**Issue by fiji-flo** [goeuro/myke#92]
```
project: foo
tasks:
    off:
        cmd: echo hello
```

yields:
```
 PROJECT | TAGS | TASKS 
---------+------+-------
 foo     |      | off   
```
